### ISSUE TITLE
Categories with different capitalization are not matched

### ISSUE THREAD

**Issue by ianfhunter** [Mara-Li/YAFPA#7]
In one of my notes, I have
```
category: Productivity
```
and in another
```
category: productivity
```

In the published version, we use a capitalized font - so it appears like a duplicate category - rather than merging them together - or being distinguishable via casing
![image](https://user-images.githubusercontent.com/1540737/140896519-b4a2dcbc-70b2-45d3-9e39-9afaaed1cf0c.png)

**Comment by Mara-Li** [comment]
Oh, I notice that but I was to lazzy to correct it oups. I will correct the code !

**Comment by Mara-Li** [comment]
Bug found and resolved! 
Also, I opened the issue in the Yet repo, so you can also ask here now :D

**Comment by ianfhunter** [comment]
Thank you! :)
